version: "3.5"

services:
  database:
    container_name: budget_database_test
    image: postgres:14.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_test
    ports:
      - "5432:5432"
    networks:
      - budget

networks:
  budget:
    name: budget-net
